FROM python:3.10-slim

WORKDIR /app

ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mynewsdb
ENV POSTGRES_HOST=postgres
ENV POSTGRES_PORT=5432

COPY ./backend/services/requirements-admin.txt /app/backend/services/requirements.txt
RUN pip install --no-cache-dir -r /app/backend/services/requirements.txt

COPY ./backend /app/backend

ENV PYTHONPATH=/app

CMD ["bash", "-c", "PYTHONPATH=/app uvicorn backend.services.admin_service:app --host 0.0.0.0 --port 8003"]

