FROM python:3.10-slim

WORKDIR /app

COPY ./KiwoomGateway/requirements-stock.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./KiwoomGateway/stock_service.py /app/

CMD ["uvicorn", "stock_service:app", "--host", "0.0.0.0", "--port", "8001"]
