name: Generate and Deploy Static Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install "psycopg[binary,pool]" python-dotenv

      - name: Generate data file
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python KiwoomGateway/generate_stock_file.py

      - name: Verify file creation
        run: |
          echo "--- Verifying file existence and content ---"
          ls -lR public
          echo "--- stocks.json content (first 5 lines) ---"
          head -n 5 public/data/stocks.json || echo "stocks.json not found or empty."

      - name: Commit and push if data changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/stocks.json
          if git diff --staged --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "Automated: Update stock data"
            git push
          fi
